// Research areas shown as tags on each card. Jev picks one group, then one area
// inside that group (two calls, because a single choice over ~190 options is
// too wide). Built from ICLR/NeurIPS primary areas, ACL ARR tracks and the
// Papers with Code task areas, plus LLM-era topics those lists lack.
// Area keys are stored in papers.area, so rename labels freely but keep keys.

type Group = { label: string; criteria: string; areas: Record<string, string> };

export const AREA_GROUPS: Record<string, Group> = {
  llm: {
    label: "Language models",
    criteria: "Training, prompting, evaluating or analyzing large language models",
    areas: {
      llm_pretraining: "LLM pretraining & scaling laws",
      instruction_tuning: "Instruction tuning",
      alignment_rlhf: "Alignment & preference optimization",
      llm_reasoning: "LLM reasoning & chain of thought",
      math_reasoning: "Mathematical reasoning",
      code_generation: "Code generation",
      in_context: "In-context learning & prompting",
      long_context: "Long-context modeling",
      rag: "Retrieval-augmented generation",
      hallucination: "Hallucination & factuality",
      llm_eval: "LLM evaluation & benchmarks",
      reward_modeling: "Reward models & LLM-as-a-judge",
      test_time_compute: "Test-time compute",
      tokenization: "Tokenization",
    },
  },
  agents: {
    label: "Agents",
    criteria: "Autonomous agents that plan, use tools, remember, or act in environments",
    areas: {
      llm_agents: "LLM agents & planning",
      agent_memory: "Agent memory",
      tool_use: "Tool use & function calling",
      multi_agent_llm: "Multi-agent LLM systems",
      web_agents: "Web & GUI agents",
      software_agents: "Software engineering agents",
      embodied_agents: "Embodied agents",
      agent_eval: "Agent benchmarks & environments",
    },
  },
  efficiency: {
    label: "Efficient ML",
    criteria: "Making models smaller, faster or cheaper to train or serve",
    areas: {
      knowledge_distillation: "Knowledge distillation",
      reasoning_distillation: "Reasoning distillation",
      quantization: "Quantization",
      pruning_sparsity: "Pruning & sparsity",
      efficient_inference: "Efficient inference & serving",
      efficient_attention: "Efficient attention & state-space models",
      peft: "Parameter-efficient fine-tuning",
      moe: "Mixture of experts",
      efficient_training: "Efficient & distributed training",
      ml_systems: "ML systems & compilers",
      on_device: "On-device ML",
    },
  },
  editing: {
    label: "Model editing & adaptation",
    criteria: "Changing what a trained model knows or does after training",
    areas: {
      knowledge_editing: "Knowledge editing",
      unlearning: "Machine unlearning",
      model_merging: "Model merging",
      continual_learning: "Continual learning",
      behavior_editing: "Behavior & reasoning editing",
      steering: "Activation steering",
    },
  },
  interpretability: {
    label: "Interpretability",
    criteria: "Understanding how models work internally or explaining their outputs",
    areas: {
      mech_interp: "Mechanistic interpretability",
      sparse_autoencoders: "Sparse autoencoders",
      probing: "Probing & representation analysis",
      feature_attribution: "Feature attribution",
      training_dynamics: "Training dynamics",
      explainable_ai: "Explainable AI",
    },
  },
  safety: {
    label: "Safety, security & trust",
    criteria: "Attacks, defenses, privacy, fairness, robustness or reliability of models",
    areas: {
      jailbreaks: "Jailbreaks & red teaming",
      adversarial_robustness: "Adversarial robustness",
      backdoors: "Backdoors & data poisoning",
      privacy: "Privacy",
      watermarking: "Watermarking & AI-text detection",
      fairness: "Fairness & bias",
      ai_oversight: "AI oversight & deception",
      uncertainty: "Uncertainty & calibration",
      ood: "Distribution shift & OOD detection",
    },
  },
  generative: {
    label: "Generative models",
    criteria: "Models that generate images, video, 3D or other data",
    areas: {
      diffusion: "Diffusion models",
      flow_matching: "Flow matching",
      text_to_image: "Text-to-image",
      video_generation: "Video generation",
      gen_3d: "3D generation",
      image_editing: "Image editing",
      gans_vaes: "GANs & VAEs",
      autoregressive_gen: "Autoregressive generation",
      controllable_gen: "Controllable generation",
    },
  },
  vision: {
    label: "Computer vision",
    criteria: "Understanding images, video or 3D scenes",
    areas: {
      recognition: "Image recognition",
      detection: "Object detection",
      segmentation: "Segmentation",
      vision_backbones: "Vision backbones",
      ssl_vision: "Self-supervised vision",
      video_understanding: "Video understanding",
      vision_3d: "3D vision & reconstruction",
      pose_motion: "Pose & motion",
      restoration: "Image restoration",
      documents: "OCR & documents",
      remote_sensing: "Remote sensing",
      driving: "Autonomous driving",
    },
  },
  multimodal: {
    label: "Multimodal",
    criteria: "Models that combine vision, language, audio or other modalities",
    areas: {
      vlm: "Vision-language models",
      multimodal_reasoning: "Multimodal reasoning",
      vqa_captioning: "VQA & captioning",
      visual_grounding: "Visual grounding",
      video_llm: "Video-language models",
      multimodal_hallucination: "Multimodal hallucination",
      unified_multimodal: "Unified multimodal models",
    },
  },
  nlp: {
    label: "NLP tasks",
    criteria: "Classic language tasks and linguistic analysis, beyond LLM training itself",
    areas: {
      translation: "Machine translation",
      summarization: "Summarization",
      qa: "Question answering",
      information_extraction: "Information extraction",
      dialogue: "Dialogue systems",
      sentiment_argument: "Sentiment & argument mining",
      multilingual: "Multilingual NLP",
      text_classification: "Text classification",
      css: "Computational social science",
      linguistics: "Linguistics & psycholinguistics",
      nlg_eval: "Generation evaluation",
    },
  },
  speech: {
    label: "Speech & audio",
    criteria: "Speech, sound or music",
    areas: {
      asr: "Speech recognition",
      tts: "Speech synthesis",
      spoken_lm: "Spoken language models",
      audio_understanding: "Audio understanding",
      music: "Music",
      speech_enhancement: "Speech enhancement",
    },
  },
  graphs: {
    label: "Graphs",
    criteria: "Learning on graphs, networks or knowledge graphs",
    areas: {
      gnn: "Graph neural networks",
      graph_transformers: "Graph transformers",
      knowledge_graphs: "Knowledge graphs",
      graph_llm: "Graphs & LLMs",
      graph_generation: "Graph generation",
      link_prediction: "Link prediction",
      dynamic_graphs: "Dynamic graphs",
      hypergraphs: "Hypergraphs",
    },
  },
  time_series: {
    label: "Time series",
    criteria: "Sequential measurements over time, forecasting or anomaly detection",
    areas: {
      ts_forecasting: "Time series forecasting",
      spatiotemporal: "Spatio-temporal forecasting",
      ts_foundation: "Time series foundation models",
      anomaly_detection: "Anomaly detection",
      ts_analysis: "Time series classification & imputation",
      event_sequences: "Event sequences",
    },
  },
  rl: {
    label: "Reinforcement learning",
    criteria: "Learning from reward or interaction, including RL for language models",
    areas: {
      deep_rl: "Deep RL",
      offline_rl: "Offline RL",
      model_based_rl: "Model-based RL",
      multi_agent_rl: "Multi-agent RL",
      rl_for_llms: "RL for LLMs",
      imitation: "Imitation learning",
      exploration: "Exploration",
      bandits: "Bandits & online learning",
      games: "Game playing",
    },
  },
  robotics: {
    label: "Robotics",
    criteria: "Robots and physical control",
    areas: {
      manipulation: "Robot manipulation",
      vla: "Vision-language-action models",
      navigation: "Navigation & SLAM",
      locomotion: "Locomotion",
      sim2real: "Sim-to-real",
      hri: "Human-robot interaction",
    },
  },
  science: {
    label: "AI for science",
    criteria: "Machine learning applied to chemistry, biology, physics, math or other sciences",
    areas: {
      molecules: "Molecules & drug discovery",
      proteins: "Proteins",
      materials: "Materials & chemistry",
      genomics: "Genomics & single-cell",
      physics_ml: "Physics-informed ML & PDEs",
      climate: "Weather & climate",
      neuroscience: "Computational neuroscience",
      ai_math: "AI for math & theorem proving",
      auto_discovery: "Automated scientific discovery",
    },
  },
  health: {
    label: "Health & medicine",
    criteria: "Clinical, medical or health applications",
    areas: {
      medical_imaging: "Medical imaging",
      brain_imaging: "Brain imaging & connectomics",
      clinical_nlp: "Clinical NLP & EHR",
      medical_llm: "Medical LLMs",
      biosignals: "Biosignals & wearables",
      mental_health: "Mental health",
    },
  },
  theory: {
    label: "Theory & foundations",
    criteria: "Mathematical or probabilistic foundations of learning",
    areas: {
      learning_theory: "Learning theory",
      optimization: "Optimization",
      dl_theory: "Deep learning theory",
      bayesian: "Bayesian & probabilistic methods",
      kernels_gp: "Kernels & Gaussian processes",
      causal: "Causal inference",
    },
  },
  paradigms: {
    label: "Learning paradigms",
    criteria: "General learning setups not tied to one modality",
    areas: {
      representation: "Representation & contrastive learning",
      meta_transfer: "Meta, transfer & few-shot learning",
      federated: "Federated learning",
      semi_weak: "Semi- & weakly supervised learning",
      domain_adaptation: "Domain adaptation",
      active_learning: "Active learning",
      automl: "AutoML & architecture search",
    },
  },
  data: {
    label: "Data, retrieval & recommendation",
    criteria: "Datasets, data quality, search, recommendation or tabular data",
    areas: {
      datasets: "Datasets & benchmarks",
      synthetic_data: "Synthetic data",
      data_curation: "Data curation",
      data_attribution: "Data attribution",
      retrieval: "Information retrieval",
      recsys: "Recommender systems",
      tabular: "Tabular data",
    },
  },
  society: {
    label: "AI & society",
    criteria: "Human-AI interaction, policy, education, economics or other social uses",
    areas: {
      hci: "Human-AI interaction",
      education: "AI in education",
      policy: "AI policy & governance",
      ethics: "Ethics & social impact",
      finance_econ: "Finance & economics",
      legal: "Legal AI",
      creative: "Creative AI",
    },
  },
  other: {
    label: "Other",
    criteria: "Not machine learning or AI research, e.g. pure physics or mathematics",
    areas: {},
  },
};

// Flat lookup: area key → label and group.
export const AREAS: Record<string, { label: string; group: string }> = Object.fromEntries(
  Object.entries(AREA_GROUPS).flatMap(([group, g]) =>
    Object.entries(g.areas).map(([key, label]) => [key, { label, group }]),
  ),
);

export const PAPER_TYPES: Record<string, { label: string; criteria: string }> = {
  method: { label: "Method", criteria: "Proposes a new model, algorithm, or training method" },
  empirical: { label: "Empirical study", criteria: "Analyzes behavior of existing methods without a new method" },
  theory: { label: "Theory", criteria: "Main contribution is proofs or formal analysis" },
  benchmark: { label: "Benchmark", criteria: "Main contribution is a dataset or benchmark" },
  survey: { label: "Survey", criteria: "Reviews existing literature" },
  system: { label: "System", criteria: "Main contribution is software, a toolkit, or infrastructure" },
};
